create or replace view DEMO_DB.STREAMABLE.TE_TIME_EMPLOYEE_MAP_VIEW(
	EMPLOYEE_EMAIL,
	EMPLOYEE_ID,
	TEAM_NAME,
	UPDATED_BY,
	UPDATED_TS
) as
  SELECT 
    EMPLOYEE_EMAIL, 
    EMPLOYEE_ID,
    TEAM_NAME,
    CURRENT_USER() AS updated_by,
    CURRENT_TIMESTAMP() AS updated_ts
  FROM EMPLOYEE_TEAM;